- name: Push pacman-contribution-graph.svg to the output branch
  uses: crazy-max/ghaction-github-pages@v3.1.0
  with:
    target_branch: output
    build_dir: .
    keep_history: false
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
